spring.application.name=greenhouse_iot
server.port=8080
server.servlet.context-path=/api

# Database Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/greenhouse_db
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# SWAGGER

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# SECURITY

jwt.expiration-ms=3600000

# JPA/Hibernate Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MQTT configuration

mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=greenhouse-backend-mqtt-client
mqtt.username=admin-user
mqtt.password=pass1234!
mqtt.dynamic-security-topic=$CONTROL/dynamic-security/v1